name: Deploy to Ubuntu

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Generate .env file
        run: |
          echo "APIKEY=${{ secrets.APIKEY }}" >> .env
          echo "APPID=${{ secrets.APPID }}" >> .env
          echo "AUTHDOMAIN=${{ secrets.AUTHDOMAIN }}" >> .env
          echo "EMAIL=${{ secrets.EMAIL }}" >> .env
          echo "FIREBASE_CLIENT_EMAIL=${{ secrets.FIREBASE_CLIENT_EMAIL }}" >> .env
          echo "FIREBASE_PRIVATE_KEY=${{ secrets.FIREBASE_PRIVATE_KEY }}" >> .env
          echo "FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}" >> .env
          echo "MAIL_API_KEY=${{ secrets.MAIL_API_KEY }}" >> .env
          echo "MEASUREMENTID=${{ secrets.MEASUREMENTID }}" >> .env
          echo "MESSAGINGSENDERID=${{ secrets.MESSAGINGSENDERID }}" >> .env
          echo "MONGO_CONNECTION=${{ secrets.MONGO_CONNECTION }}" >> .env
          echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> .env
          echo "PROJECTID=${{ secrets.PROJECTID }}" >> .env
          echo "STORAGEBUCKET"=${{ secrets.STORAGEBUCKET }}" >> .env
          echo "TOKEN_SECRET=${{ secrets.TOKEN_SECRET }}" >> .env
          echo "TWILIO_AUTH_TOKEN=${{ secrets.TWILIO_AUTH_TOKEN }}" >> .env
          echo "TWILIO_PHONE_NUMBER=${{ secrets.TWILIO_PHONE_NUMBER }}" >> .env
          echo "TWILIO_SID=${{ secrets.TWILIO_SID }}" >> .env
          
  

      - name: rsync deployments
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete --exclude 'client' --exclude 'client' --exclude 'folders' 
          path: .
          remote_path: /home/ubuntu/ef-API-Backend
          remote_host: ${{ secrets.SERVER_HOST }}
          remote_user: ${{ secrets.SERVER_USERNAME }}
          remote_key: ${{ secrets.SERVER_PRIVATE_KEY }}


      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          script: |            
            pm2 restart server
